name: EOPF-Zarr Driver Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  check-zarr-driver-dependencies:
    runs-on: ubuntu-latest
    name: Check Zarr Driver Dependencies
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Check Ubuntu base image updates
      run: |
        cd eopf-zarr-driver
        # Get current Ubuntu image digest
        CURRENT_DIGEST=$(docker pull ubuntu:25.04 --quiet)
        echo "Current Ubuntu 25.04 digest: $CURRENT_DIGEST"
        
        # Check if there are newer versions
        docker pull ubuntu:25.04
        NEW_DIGEST=$(docker inspect ubuntu:25.04 --format='{{.Id}}')
        echo "Latest Ubuntu 25.04 digest: $NEW_DIGEST"
        
        if [ "$CURRENT_DIGEST" != "$NEW_DIGEST" ]; then
          echo "::notice::Ubuntu base image has updates available"
        else
          echo "::notice::Ubuntu base image is up to date"
        fi
        
    - name: Check GDAL version in Ubuntu 25.04
      run: |
        # Check current GDAL version in Ubuntu 25.04
        GDAL_VERSION=$(docker run --rm ubuntu:25.04 sh -c 'apt-get update >/dev/null 2>&1 && apt-cache show gdal-bin | grep Version | head -1 | cut -d" " -f2')
        echo "::notice::Current GDAL version in Ubuntu 25.04: $GDAL_VERSION"
        
    - name: Create issue for updates
      if: success()
      uses: actions/github-script@v7
      with:
        script: |
          const title = 'Weekly EOPF-Zarr Driver Dependency Check - ' + new Date().toISOString().split('T')[0];
          const body = `Automated weekly check for EOPF-Zarr driver dependency updates.
          
          Please review:
          - Ubuntu 25.04 base image updates
          - GDAL version updates
          - Python package security updates
          
          This is an automated check. Please review the current versions and update if necessary.
          
          Related files:
          - \`eopf-zarr-driver/Dockerfile\`
          - \`eopf-zarr-driver/docker-compose.yml\`
          `;
          
          // Check if issue already exists
          const issues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            labels: 'dependencies,zarr-driver'
          });
          
          const existingIssue = issues.data.find(issue => 
            issue.title.includes('Weekly EOPF-Zarr Driver Dependency Check')
          );
          
          if (!existingIssue) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['dependencies', 'zarr-driver', 'automated']
            });
          } else {
            console.log('Weekly dependency check issue already exists');
          }
